// <auto-generated />
using MVC_Task2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Task2.Migrations
{
    [DbContext(typeof(WebAppContext))]
    partial class WebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Task2.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Degree")
                        .HasColumnType("real");

                    b.Property<float>("MinDegree")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100f,
                            MinDegree = 60f,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 120f,
                            MinDegree = 70f,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 150f,
                            MinDegree = 100f,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 80f,
                            MinDegree = 65f,
                            Name = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100f,
                            MinDegree = 55f,
                            Name = "Web Fundamentals"
                        });
                });

            modelBuilder.Entity("MVC_Task2.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<float>("Degree")
                        .HasColumnType("real");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CourseResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Degree = 80f,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            Degree = 90f,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 5,
                            Degree = 75f,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Degree = 90f,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Degree = 95f,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 4,
                            Degree = 70f,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 5,
                            Degree = 90f,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            Degree = 140f,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            Degree = 90f,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            Degree = 110f,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            Degree = 60f,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 5,
                            Degree = 80f,
                            TraineeId = 7
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 4,
                            Degree = 60f,
                            TraineeId = 7
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 1,
                            Degree = 80f,
                            TraineeId = 7
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 4,
                            Degree = 80f,
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 3,
                            Degree = 120f,
                            TraineeId = 6
                        });
                });

            modelBuilder.Entity("MVC_Task2.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "Ali",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "Raouf",
                            Name = "SWE"
                        },
                        new
                        {
                            Id = 3,
                            ManagerName = "Hassan",
                            Name = "IS"
                        },
                        new
                        {
                            Id = 4,
                            ManagerName = "Moataz",
                            Name = "DS"
                        });
                });

            modelBuilder.Entity("MVC_Task2.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Moatam",
                            CourseId = 1,
                            DepartmentId = 2,
                            ImagePath = "1.jpg",
                            Name = "Dr.Khaled",
                            Salary = 5000f
                        },
                        new
                        {
                            Id = 2,
                            Address = "El-zahraa",
                            CourseId = 5,
                            DepartmentId = 1,
                            ImagePath = "3.jpg",
                            Name = "Dr.Mona",
                            Salary = 15000f
                        },
                        new
                        {
                            Id = 3,
                            Address = "Agouza",
                            CourseId = 1,
                            DepartmentId = 2,
                            ImagePath = "2.jpg",
                            Name = "Dr.Sara",
                            Salary = 8000f
                        },
                        new
                        {
                            Id = 4,
                            Address = "October",
                            CourseId = 5,
                            DepartmentId = 3,
                            ImagePath = "1.jpg",
                            Name = "Dr.Sally",
                            Salary = 9000f
                        },
                        new
                        {
                            Id = 5,
                            Address = "Alex",
                            CourseId = 2,
                            DepartmentId = 4,
                            ImagePath = "3.jpg",
                            Name = "Dr.Ismail",
                            Salary = 10000f
                        },
                        new
                        {
                            Id = 6,
                            Address = "El-Rehab",
                            CourseId = 3,
                            DepartmentId = 4,
                            ImagePath = "4.jpg",
                            Name = "Dr.Sami",
                            Salary = 20000f
                        },
                        new
                        {
                            Id = 7,
                            Address = "Aswan",
                            CourseId = 4,
                            DepartmentId = 1,
                            ImagePath = "2.jpg",
                            Name = "Dr.Samir",
                            Salary = 12000f
                        },
                        new
                        {
                            Id = 8,
                            Address = "Nasr City",
                            CourseId = 5,
                            DepartmentId = 3,
                            ImagePath = "4.jpg",
                            Name = "Dr.Mahmoud",
                            Salary = 11000f
                        });
                });

            modelBuilder.Entity("MVC_Task2.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Grade")
                        .HasColumnType("real");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Giza",
                            Grade = 150f,
                            ImagePath = "1.jpg",
                            Name = "Abdo"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo",
                            Grade = 180f,
                            ImagePath = "2.jpg",
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            Grade = 200f,
                            ImagePath = "3.jpg",
                            Name = "Khaled"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Aswan",
                            Grade = 120f,
                            ImagePath = "4.jpg",
                            Name = "Loay"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Maadi",
                            Grade = 115f,
                            ImagePath = "1.jpg",
                            Name = "Ibrahem"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nasr City",
                            Grade = 190f,
                            ImagePath = "2.jpg",
                            Name = "Fawzy"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Dokki",
                            Grade = 100f,
                            ImagePath = "3.jpg",
                            Name = "Mohamed"
                        });
                });

            modelBuilder.Entity("MVC_Task2.Models.CourseResult", b =>
                {
                    b.HasOne("MVC_Task2.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Task2.Models.Trainee", "Trainee")
                        .WithMany("CourseResult")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("MVC_Task2.Models.Instructor", b =>
                {
                    b.HasOne("MVC_Task2.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Task2.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_Task2.Models.Course", b =>
                {
                    b.Navigation("CourseResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("MVC_Task2.Models.Department", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("MVC_Task2.Models.Trainee", b =>
                {
                    b.Navigation("CourseResult");
                });
#pragma warning restore 612, 618
        }
    }
}
